[2016-04-14 19:45:34,968: INFO/MainProcess] Connected to redis://172.20.14.29:6379/0
[2016-04-14 19:45:35,006: INFO/MainProcess] mingle: searching for neighbors
[2016-04-14 19:45:36,030: INFO/MainProcess] mingle: all alone
[2016-04-14 19:45:36,087: WARNING/MainProcess] celery@mailNode ready.
[2016-04-14 19:45:36,324: INFO/MainProcess] Received task: spider_worker.celery.sendMail[a100d028-cee7-498e-9eed-4c8784bcdb60]
[2016-04-14 19:45:36,346: INFO/MainProcess] Received task: spider_worker.celery.sendMail[9338e46e-ceb9-40c1-87da-6d17364e34db]
[2016-04-14 19:45:36,379: INFO/MainProcess] Received task: spider_worker.celery.sendMail[fe0ab6da-1d6e-4f91-a0ed-294db8ce466f]
[2016-04-14 19:45:36,406: INFO/MainProcess] Received task: spider_worker.celery.sendMail[446a8644-1ff9-4dd1-8ef5-043a009f2984]
[2016-04-14 19:45:36,428: INFO/MainProcess] Received task: spider_worker.celery.sendMail[478de600-a4de-434e-a969-e8743b439bda]
[2016-04-14 19:45:37,960: INFO/Worker-3] spider_worker.celery.sendMail[fe0ab6da-1d6e-4f91-a0ed-294db8ce466f]: send mail to liufengb@yonyou.com
[2016-04-14 19:45:37,979: ERROR/MainProcess] Task spider_worker.celery.sendMail[fe0ab6da-1d6e-4f91-a0ed-294db8ce466f] raised unexpected: AttributeError("type object 'ReportSendLog' has no attribute 'query'",)
Traceback (most recent call last):
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/celery.py", line 186, in sendMail
    set_mail_status(report_send_id, mail_to, is_success)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/uradar.py", line 46, in set_mail_status
    report_send = ReportSendLog.query.filter(
AttributeError: type object 'ReportSendLog' has no attribute 'query'
[2016-04-14 19:45:38,084: INFO/Worker-1] spider_worker.celery.sendMail[a100d028-cee7-498e-9eed-4c8784bcdb60]: send mail to liufengb@yonyou.com
[2016-04-14 19:45:38,102: ERROR/MainProcess] Task spider_worker.celery.sendMail[a100d028-cee7-498e-9eed-4c8784bcdb60] raised unexpected: AttributeError("type object 'ReportSendLog' has no attribute 'query'",)
Traceback (most recent call last):
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/celery.py", line 186, in sendMail
    set_mail_status(report_send_id, mail_to, is_success)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/uradar.py", line 46, in set_mail_status
    report_send = ReportSendLog.query.filter(
AttributeError: type object 'ReportSendLog' has no attribute 'query'
[2016-04-14 19:45:38,163: INFO/Worker-4] spider_worker.celery.sendMail[446a8644-1ff9-4dd1-8ef5-043a009f2984]: send mail to liufengb@yonyou.com
[2016-04-14 19:45:38,168: INFO/Worker-2] spider_worker.celery.sendMail[9338e46e-ceb9-40c1-87da-6d17364e34db]: send mail to liufengb@yonyou.com
[2016-04-14 19:45:38,188: ERROR/MainProcess] Task spider_worker.celery.sendMail[9338e46e-ceb9-40c1-87da-6d17364e34db] raised unexpected: AttributeError("type object 'ReportSendLog' has no attribute 'query'",)
Traceback (most recent call last):
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/celery.py", line 186, in sendMail
    set_mail_status(report_send_id, mail_to, is_success)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/uradar.py", line 46, in set_mail_status
    report_send = ReportSendLog.query.filter(
AttributeError: type object 'ReportSendLog' has no attribute 'query'
[2016-04-14 19:45:38,189: ERROR/MainProcess] Task spider_worker.celery.sendMail[446a8644-1ff9-4dd1-8ef5-043a009f2984] raised unexpected: AttributeError("type object 'ReportSendLog' has no attribute 'query'",)
Traceback (most recent call last):
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/celery.py", line 186, in sendMail
    set_mail_status(report_send_id, mail_to, is_success)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/uradar.py", line 46, in set_mail_status
    report_send = ReportSendLog.query.filter(
AttributeError: type object 'ReportSendLog' has no attribute 'query'
[2016-04-14 19:45:39,800: INFO/Worker-1] spider_worker.celery.sendMail[478de600-a4de-434e-a969-e8743b439bda]: send mail to liufengb@yonyou.com
[2016-04-14 19:45:39,804: ERROR/MainProcess] Task spider_worker.celery.sendMail[478de600-a4de-434e-a969-e8743b439bda] raised unexpected: AttributeError("type object 'ReportSendLog' has no attribute 'query'",)
Traceback (most recent call last):
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/celery.py", line 186, in sendMail
    set_mail_status(report_send_id, mail_to, is_success)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/uradar.py", line 46, in set_mail_status
    report_send = ReportSendLog.query.filter(
AttributeError: type object 'ReportSendLog' has no attribute 'query'
[2016-04-14 19:45:42,340: INFO/MainProcess] Received task: spider_worker.celery.sendMail[dc610c48-4eb6-429f-a2a6-48da40b06a0c]
[2016-04-14 19:45:44,087: INFO/Worker-2] spider_worker.celery.sendMail[dc610c48-4eb6-429f-a2a6-48da40b06a0c]: send mail to liufengb@yonyou.com
[2016-04-14 19:45:44,092: ERROR/MainProcess] Task spider_worker.celery.sendMail[dc610c48-4eb6-429f-a2a6-48da40b06a0c] raised unexpected: AttributeError("type object 'ReportSendLog' has no attribute 'query'",)
Traceback (most recent call last):
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/celery.py", line 186, in sendMail
    set_mail_status(report_send_id, mail_to, is_success)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/uradar.py", line 46, in set_mail_status
    report_send = ReportSendLog.query.filter(
AttributeError: type object 'ReportSendLog' has no attribute 'query'
[2016-04-14 19:46:20,746: INFO/MainProcess] Received task: spider_worker.celery.sendMail[f311c25b-164f-4141-95f1-dda8da65ce81]
[2016-04-14 19:46:22,347: INFO/Worker-3] spider_worker.celery.sendMail[f311c25b-164f-4141-95f1-dda8da65ce81]: send mail to liufengb@yonyou.com
[2016-04-14 19:46:22,352: ERROR/MainProcess] Task spider_worker.celery.sendMail[f311c25b-164f-4141-95f1-dda8da65ce81] raised unexpected: AttributeError("type object 'ReportSendLog' has no attribute 'query'",)
Traceback (most recent call last):
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/celery.py", line 186, in sendMail
    set_mail_status(report_send_id, mail_to, is_success)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/uradar.py", line 46, in set_mail_status
    report_send = ReportSendLog.query.filter(
AttributeError: type object 'ReportSendLog' has no attribute 'query'
[2016-04-14 19:47:33,793: INFO/MainProcess] Received task: spider_worker.celery.sendMail[9f6b6436-ebcc-4525-9990-f2cb163398b7]
[2016-04-14 19:47:35,743: INFO/Worker-4] spider_worker.celery.sendMail[9f6b6436-ebcc-4525-9990-f2cb163398b7]: send mail to liufengb@yonyou.com
[2016-04-14 19:47:35,748: ERROR/MainProcess] Task spider_worker.celery.sendMail[9f6b6436-ebcc-4525-9990-f2cb163398b7] raised unexpected: AttributeError("type object 'ReportSendLog' has no attribute 'query'",)
Traceback (most recent call last):
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/celery.py", line 186, in sendMail
    set_mail_status(report_send_id, mail_to, is_success)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/uradar.py", line 46, in set_mail_status
    report_send = ReportSendLog.query.filter(
AttributeError: type object 'ReportSendLog' has no attribute 'query'
[2016-04-14 19:49:42,250: WARNING/MainProcess] Exception
[2016-04-14 19:49:42,251: WARNING/MainProcess] KeyError
[2016-04-14 19:49:42,251: WARNING/MainProcess] :
[2016-04-14 19:49:42,251: WARNING/MainProcess] KeyError(140735236857856,)
[2016-04-14 19:49:42,251: WARNING/MainProcess] in
[2016-04-14 19:49:42,251: WARNING/MainProcess] <module 'threading' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'>
[2016-04-14 19:49:42,251: WARNING/MainProcess] ignored
[2016-04-14 19:57:22,817: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/0: .
Trying again in 2.00 seconds...

[2016-04-14 19:57:24,836: ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/0: .
Trying again in 4.00 seconds...

[2016-04-14 19:57:28,157: WARNING/MainProcess] Exception
[2016-04-14 19:57:28,158: WARNING/MainProcess] KeyError
[2016-04-14 19:57:28,158: WARNING/MainProcess] :
[2016-04-14 19:57:28,158: WARNING/MainProcess] KeyError(140735236857856,)
[2016-04-14 19:57:28,158: WARNING/MainProcess] in
[2016-04-14 19:57:28,159: WARNING/MainProcess] <module 'threading' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'>
[2016-04-14 19:57:28,159: WARNING/MainProcess] ignored
[2016-04-14 19:57:42,447: INFO/MainProcess] Connected to redis://172.20.14.29:6379/0
[2016-04-14 19:57:42,488: INFO/MainProcess] mingle: searching for neighbors
[2016-04-14 19:57:43,513: INFO/MainProcess] mingle: all alone
[2016-04-14 19:57:43,570: WARNING/MainProcess] celery@mailNode ready.
[2016-04-14 19:57:55,375: INFO/MainProcess] Received task: spider_worker.celery.sendMail[28ace374-be0c-4516-a1dd-6194d93eeb4d]
[2016-04-14 19:57:57,115: INFO/Worker-1] spider_worker.celery.sendMail[28ace374-be0c-4516-a1dd-6194d93eeb4d]: send mail to liufengb@yonyou.com
[2016-04-14 19:57:57,136: ERROR/MainProcess] Task spider_worker.celery.sendMail[28ace374-be0c-4516-a1dd-6194d93eeb4d] raised unexpected: AttributeError("type object 'ReportSendLog' has no attribute 'query'",)
Traceback (most recent call last):
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/celery.py", line 190, in sendMail
    set_mail_status(report_send_id, mail_to, is_success)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/uradar.py", line 46, in set_mail_status
    report_send = ReportSendLog.query.filter(
AttributeError: type object 'ReportSendLog' has no attribute 'query'
[2016-04-14 19:58:28,874: INFO/MainProcess] Received task: spider_worker.celery.sendMail[1707ee4a-b61c-4a95-8409-0ca041d3dc3a]
[2016-04-14 19:58:30,601: INFO/Worker-2] spider_worker.celery.sendMail[1707ee4a-b61c-4a95-8409-0ca041d3dc3a]: send mail to liufengb@yonyou.com
[2016-04-14 19:58:30,787: ERROR/MainProcess] Task spider_worker.celery.sendMail[1707ee4a-b61c-4a95-8409-0ca041d3dc3a] raised unexpected: AttributeError("type object 'ReportSendLog' has no attribute 'query'",)
Traceback (most recent call last):
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/liufeng/.virtualenvs/spider/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/celery.py", line 190, in sendMail
    set_mail_status(report_send_id, mail_to, is_success)
  File "/Users/liufeng/Code/work/spider/utils/tools/spider_worker/uradar.py", line 46, in set_mail_status
    report_send = ReportSendLog.query.filter(
AttributeError: type object 'ReportSendLog' has no attribute 'query'
[2016-04-14 19:59:23,743: WARNING/MainProcess] Exception
[2016-04-14 19:59:23,744: WARNING/MainProcess] KeyError
[2016-04-14 19:59:23,744: WARNING/MainProcess] :
[2016-04-14 19:59:23,744: WARNING/MainProcess] KeyError(140735236857856,)
[2016-04-14 19:59:23,744: WARNING/MainProcess] in
[2016-04-14 19:59:23,744: WARNING/MainProcess] <module 'threading' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'>
[2016-04-14 19:59:23,744: WARNING/MainProcess] ignored
